"""Normal Python package for the canonical release lifecycle."""

from .changelog import (
    changelog_spec,
    changelog_text,
    changelog_text_from_text,
    check_changelog,
    prepare_changelog_bytes,
    release_heading_for,
    target_heading_matches,
    unreleased_section,
    validate_date,
)
from .configuration import load_config, normalized_relative_path, parse_version_files, repository_root
from .foundation import LIFECYCLE_MODES, SEMVER_RE, ReleaseError, StatusRecord, VersionFile, run_git
from .lifecycle_checks import (
    allowed_release_paths,
    command_check,
    command_check_source,
    command_commit,
    command_prepare,
    command_release_ready,
    configured_versions,
    release_commit_paths,
    source_state,
    validate_release_ready_state,
)
from .lifecycle_tags import command_tag, command_tag_ready, command_verify_tag, validate_tag_ready_state
from .repository_state import (
    current_head,
    ensure_clean,
    lifecycle_message,
    status_paths,
    status_records,
    tag_exists,
    tag_name,
)
from .transaction import atomic_apply
from .version_files import (
    check_forbidden_patterns,
    compare_versions,
    file_bytes,
    json_pointer_parts,
    read_json_pointer,
    read_version,
    render_version,
    semver_key,
    toml_version_location,
    validate_semver,
    write_json_pointer,
)
from .cli import build_parser, main

__all__ = [
    "ReleaseError",
    "LIFECYCLE_MODES",
    "SEMVER_RE",
    "StatusRecord",
    "VersionFile",
    "allowed_release_paths",
    "atomic_apply",
    "build_parser",
    "changelog_spec",
    "changelog_text",
    "changelog_text_from_text",
    "check_changelog",
    "check_forbidden_patterns",
    "command_check",
    "command_check_source",
    "command_commit",
    "command_prepare",
    "command_release_ready",
    "command_tag",
    "command_tag_ready",
    "command_verify_tag",
    "compare_versions",
    "configured_versions",
    "current_head",
    "ensure_clean",
    "file_bytes",
    "json_pointer_parts",
    "lifecycle_message",
    "load_config",
    "main",
    "normalized_relative_path",
    "parse_version_files",
    "prepare_changelog_bytes",
    "read_json_pointer",
    "read_version",
    "release_commit_paths",
    "release_heading_for",
    "render_version",
    "repository_root",
    "run_git",
    "semver_key",
    "source_state",
    "status_paths",
    "status_records",
    "tag_exists",
    "tag_name",
    "target_heading_matches",
    "toml_version_location",
    "unreleased_section",
    "validate_date",
    "validate_release_ready_state",
    "validate_semver",
    "validate_tag_ready_state",
    "write_json_pointer",
]
