package sqlitestore

func sharedSchemaTables() []migrationTableSpec {
	return []migrationTableSpec{
		{name: "shared_tasks", create: `CREATE TABLE IF NOT EXISTS shared_tasks (id TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload BLOB NOT NULL, updated_at TEXT NOT NULL)`, columns: []string{"id", "revision", "payload", "updated_at"}},
		{name: "shared_trains", create: `CREATE TABLE IF NOT EXISTS shared_trains (id TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload BLOB NOT NULL, updated_at TEXT NOT NULL)`, columns: []string{"id", "revision", "payload", "updated_at"}},
		{name: "shared_adrs", create: `CREATE TABLE IF NOT EXISTS shared_adrs (id TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload BLOB NOT NULL, updated_at TEXT NOT NULL)`, columns: []string{"id", "revision", "payload", "updated_at"}},
		{name: "shared_rules", create: `CREATE TABLE IF NOT EXISTS shared_rules (id TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload BLOB NOT NULL, updated_at TEXT NOT NULL)`, columns: []string{"id", "revision", "payload", "updated_at"}},
		{name: "shared_journals", create: `CREATE TABLE IF NOT EXISTS shared_journals (id TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload BLOB NOT NULL, updated_at TEXT NOT NULL)`, columns: []string{"id", "revision", "payload", "updated_at"}},
		{name: "shared_replication", create: `CREATE TABLE IF NOT EXISTS shared_replication (entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, last_revision INTEGER NOT NULL, last_synced_at TEXT, PRIMARY KEY(entity_type, entity_id))`, columns: []string{"entity_type", "entity_id", "last_revision", "last_synced_at"}},
		{name: "hub_outbox", create: `CREATE TABLE IF NOT EXISTS hub_outbox (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, project_id TEXT NOT NULL DEFAULT '', revision INTEGER NOT NULL, kind TEXT NOT NULL, payload BLOB NOT NULL, created_at TEXT NOT NULL, published_at TEXT, attempt INTEGER NOT NULL DEFAULT 0, last_error_code TEXT, next_attempt_at TEXT, operation_id TEXT NOT NULL DEFAULT '', request_sha256 TEXT NOT NULL DEFAULT '', attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT NOT NULL DEFAULT '')`, columns: []string{"id", "entity_type", "entity_id", "project_id", "revision", "kind", "payload", "created_at", "published_at", "attempt", "last_error_code", "next_attempt_at", "operation_id", "request_sha256", "attempts", "last_error"}, addColumns: map[string]string{"project_id": `ALTER TABLE hub_outbox ADD COLUMN project_id TEXT NOT NULL DEFAULT ''`, "attempt": `ALTER TABLE hub_outbox ADD COLUMN attempt INTEGER NOT NULL DEFAULT 0`, "last_error_code": `ALTER TABLE hub_outbox ADD COLUMN last_error_code TEXT`, "next_attempt_at": `ALTER TABLE hub_outbox ADD COLUMN next_attempt_at TEXT`, "operation_id": `ALTER TABLE hub_outbox ADD COLUMN operation_id TEXT NOT NULL DEFAULT ''`, "request_sha256": `ALTER TABLE hub_outbox ADD COLUMN request_sha256 TEXT NOT NULL DEFAULT ''`, "attempts": `ALTER TABLE hub_outbox ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0`, "last_error": `ALTER TABLE hub_outbox ADD COLUMN last_error TEXT NOT NULL DEFAULT ''`}},
		{name: "replication_state", create: `CREATE TABLE IF NOT EXISTS replication_state (id INTEGER PRIMARY KEY CHECK(id = 1), status TEXT NOT NULL, cursor TEXT NOT NULL DEFAULT '', last_success_at TEXT, oldest_pending_at TEXT, pending_count INTEGER NOT NULL DEFAULT 0, failed_count INTEGER NOT NULL DEFAULT 0, last_error_code TEXT, attempt INTEGER NOT NULL DEFAULT 0, next_attempt_at TEXT, updated_at TEXT NOT NULL)`, columns: []string{"id", "status", "cursor", "last_success_at", "oldest_pending_at", "pending_count", "failed_count", "last_error_code", "attempt", "next_attempt_at", "updated_at"}},
		{name: "shared_authority", create: `CREATE TABLE IF NOT EXISTS shared_authority (id INTEGER PRIMARY KEY CHECK(id = 1), mode TEXT NOT NULL, baseline_revision TEXT NOT NULL, baseline_digest TEXT NOT NULL, cutover_at TEXT NOT NULL)`, columns: []string{"id", "mode", "baseline_revision", "baseline_digest", "cutover_at"}},
		{name: "shared_operations", create: `CREATE TABLE IF NOT EXISTS shared_operations (operation_id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, revision INTEGER NOT NULL, request_sha256 TEXT NOT NULL, result_payload BLOB NOT NULL, created_at TEXT NOT NULL)`, columns: []string{"operation_id", "entity_type", "entity_id", "revision", "request_sha256", "result_payload", "created_at"}},
		{name: "shared_project_identifiers", create: `CREATE TABLE IF NOT EXISTS shared_project_identifiers (project_id TEXT PRIMARY KEY, project_code TEXT NOT NULL, next_task_number INTEGER NOT NULL, next_adr_number INTEGER NOT NULL, next_rule_number INTEGER NOT NULL, next_journal_number INTEGER NOT NULL, next_train_number INTEGER NOT NULL)`, columns: []string{"project_id", "project_code", "next_task_number", "next_adr_number", "next_rule_number", "next_journal_number", "next_train_number"}},
		{name: "shared_train_task_admissions", create: `CREATE TABLE IF NOT EXISTS shared_train_task_admissions (project_id TEXT NOT NULL, task_id TEXT NOT NULL, train_id TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(project_id, task_id))`, columns: []string{"project_id", "task_id", "train_id", "created_at"}},
		{name: "shared_task_sequences", create: `CREATE TABLE IF NOT EXISTS shared_task_sequences (project_id TEXT PRIMARY KEY, project_code TEXT NOT NULL, next_task_number INTEGER NOT NULL)`, columns: []string{"project_id", "project_code", "next_task_number"}},
		{name: "shared_integration_receipts", create: `CREATE TABLE IF NOT EXISTS shared_integration_receipts (id TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload BLOB NOT NULL, updated_at TEXT NOT NULL)`, columns: []string{"id", "revision", "payload", "updated_at"}},
		{name: "shared_bootstrap_markers", create: `CREATE TABLE IF NOT EXISTS shared_bootstrap_markers (project_id TEXT PRIMARY KEY, hub_revision TEXT NOT NULL, completed_at TEXT NOT NULL)`, columns: []string{"project_id", "hub_revision", "completed_at"}},
		{name: "shared_adr_sequences", create: `CREATE TABLE IF NOT EXISTS shared_adr_sequences (project_id TEXT PRIMARY KEY, project_code TEXT NOT NULL, next_adr_number INTEGER NOT NULL)`, columns: []string{"project_id", "project_code", "next_adr_number"}},
		{name: "shared_project_configurations", create: `CREATE TABLE IF NOT EXISTS shared_project_configurations (id TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload BLOB NOT NULL, updated_at TEXT NOT NULL)`, columns: []string{"id", "revision", "payload", "updated_at"}},
		{name: "shared_entity_sequences", create: `CREATE TABLE IF NOT EXISTS shared_entity_sequences (entity_type TEXT NOT NULL, project_id TEXT NOT NULL, project_code TEXT NOT NULL, next_number INTEGER NOT NULL, PRIMARY KEY(entity_type, project_id))`, columns: []string{"entity_type", "project_id", "project_code", "next_number"}},
		{name: "shared_entity_revisions", create: `CREATE TABLE IF NOT EXISTS shared_entity_revisions (entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, project_id TEXT NOT NULL, revision INTEGER NOT NULL, mutation_kind TEXT NOT NULL, actor TEXT NOT NULL, reason TEXT NOT NULL, changed_fields BLOB NOT NULL, payload BLOB NOT NULL, recorded_at TEXT NOT NULL, PRIMARY KEY(entity_type, entity_id, revision))`, columns: []string{"entity_type", "entity_id", "project_id", "revision", "mutation_kind", "actor", "reason", "changed_fields", "payload", "recorded_at"}},
	}
}
